### ISSUE TITLE
Lint action breaks github actions

### ISSUE THREAD

**Issue by ansiblejunky** [astral-sh/ruff-action#111]
I've created a lint action for Github that runs a couple commands, but it is breaking the whole pipeline. Meaning, if I run it before my other command and it finds an error in python code, it lists the error and then stops ALL processing going forward... it doesn't run my next command at all. 

Example github action with an `echo` command afterwards to show it never runs:
```
name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - run: echo "test"
 ```
Action runs upon `push` to master branch, but it fails and never runs echo command.
[Example with my repo](https://github.com/ansiblejunky/ansible-project-template/actions/runs/14091142149/job/39467854829)
