### ISSUE TITLE
v2 versions already showing in Dependabot

### ISSUE THREAD

**Issue by amrishparmar** [astral-sh/ruff-action#19]
Not a big deal, but noticed in the regular Dependabot updates that v2 is showing up (presumably created from the new `v2` and `v2-test`), despite it not officially being released yet (v1.1.1 still shows as latest version in the repo and Marketplace)

![Image](https://github.com/user-attachments/assets/388b5cd7-0324-4f7b-92e7-b49f970f8edf)

Relevant `dependabot.yml` section:

```yaml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      ...
```
