### ISSUE TITLE
Feature to both lint and check format in a single action

### ISSUE THREAD

**Issue by augustelalande** [astral-sh/ruff-action#23]
I would like an option to also check formatting in addition to the default lint check. As far as I can tell this is not possible even playing with the args as it is today (I'm away of https://github.com/astral-sh/ruff/issues/8232).

My ideal invocation would be
```yaml
- uses: astral-sh/ruff-action@v2
  with:
    check_format: true
```

I'm willing to contribute it if people find it useful.

**Comment by eifinger** [comment]
You can currently achieve this with either [using the installed ruff](https://github.com/astral-sh/ruff-action?tab=readme-ov-file#use-to-install-ruff)

```yaml
- uses: astral-sh/ruff-action@v2
- run: ruff format
```

or using the action several times.

```yaml
- uses: astral-sh/ruff-action@v2
- uses: astral-sh/ruff-action@v2
  with:
    args: "format --check"
```

I am hesitant to include a temporary workaround in this action with https://github.com/astral-sh/ruff/issues/8232 already being discussed, because it means more maintenance overhead, possible breaking changes etc.

**Comment by daveisfera** [comment]
Might not be worth the trouble, but another way to consider it is that the action could currently abstract away the fact that it's 2 commands and then there wouldn't be a need for a workflow change once `ruff` support doing both natively

**Comment by Avasam** [comment]
If you want both lint and format checks to appear in the logs, you need to also add `if: ${{ !cancelled() }}`

This:
```yaml
  Ruff:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          version-file: backend/pyproject.toml
          src: backend
      - run: ruff format --check
        # Check formatting even if the the previous step failed
        if: ${{ !cancelled() }}
```

Could become this:
```yaml
  Ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          version-file: backend/pyproject.toml
          src: backend
          lint-and-format-check: true
```
