### ISSUE TITLE
'Failed to download from' 'Unexpected HTTP response: 404'

### ISSUE THREAD

**Issue by alex-shef** [astral-sh/ruff-action#27]
`##[debug]Failed to download from "https://github.com/astral-sh/ruff/releases/download/2.0.0/ruff-x86_64-unknown-linux-gnu.tar.gz". Code(404) Message(Not Found)
Error: Unexpected HTTP response: 404`

```
    steps:
      - name: Ruff
        uses: astral-sh/ruff-action@v2
        with:
          version: "2.0.0"
```
