### ISSUE TITLE
args: "--exit-zero" --> error: unexpected argument '--exit-zero' found

### ISSUE THREAD

**Issue by cclauss** [astral-sh/ruff-action#52]
I want to be able to show the lint errors but not crash the GitHub Action.
```yaml
      - uses: astral-sh/ruff-action@v3
        with:
          args: "--exit-zero"  # TODO: Fix the errors and remove this line
```
> error: unexpected argument '--exit-zero' found

https://docs.astral.sh/ruff/linter/#exit-codes
