### ISSUE TITLE
[suggestion]Support lock files (uv, poetry) for version install

### ISSUE THREAD

**Issue by orenm-gloat** [astral-sh/ruff-action#55]
Following the addition of `pyproject.toml` support I think there is still a gap where the pyproject can have sem ver range and the actual version installed may differ.
Adding parsing of lock file can overcome this.
Another option may be to add an option to opt out and use the provided ruff from the project CI installation, e.g. - the repo owner needs to install his deps and make sure ruff is in the path and then the action just runs the provided ruff.

This ensures that for a given RUFF usage the same ruff is used in the local dev env and the remote CI env.

**Comment by eifinger** [comment]
I think your workflow is better suited by something like

```yaml
- name: Install the latest version of uv
  uses: astral-sh/setup-uv@v5
- name: Sync dependencies
  run: uv sync --group lint
- name: Lint with ruff
  run: ruff check
```

This way you use uv (or another tool) to make sure you install the exact same tools/versions as in your local setup and then use them.

**Comment by orenm-gloat** [comment]
yes I thought about it while writing the suggestion, but I think this misses out on the other goodies the action does, such as output format and matchers.
Adding this option, in high level, means skipping the first part of `setupRuff` or in it, if opt to use pre-installed, just use it without downloading, kind of same as if get from cache returns true for a given version

**Comment by eifinger** [comment]
Adding lock file parsing exceeds the intented functionality of this action.
For your workflow I would suggest to copy [the matchers from this repo]() and then run

```yaml
  - name: Set up matchers
    run: |
      echo "::add-matcher::path/to/check.json"
      echo "::add-matcher::path/to/format.json"
  - uses: astral-sh/setup-uv@v5
  - run: uv run ruff check
    env:
      RUFF_OUTPUT_FORMAT: github
```
