### ISSUE TITLE
Is it compatible with Github Enterprise?

### ISSUE THREAD

**Issue by thiagocrepaldi** [astral-sh/ruff-action#63]
I have created a workflow on Github Enterprise 3.12 with the following

```yaml
name: CI Code linting

on:
  push
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  linting-with-ruff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install the latest version of ruff
      uses: astral-sh/ruff-action@v3
      with:
        github_token: ${{ secrets.FULL_ACCESS_TOKEN }}
```

Note that I gave a lot more permissions than needed, I guess, and still get the "not found" as shown below:

![Image](https://github.com/user-attachments/assets/e03cdeff-47f6-4967-bf21-1c71e41436a3)

I can visit https://docs.github.com/enterprise-server@3.12/rest/releases/releases#get-the-latest-release

![Image](https://github.com/user-attachments/assets/cd42356a-4c7b-4453-ab26-8ab4c36ae041)

**Comment by thiagocrepaldi** [comment]
This seems like some permission issue, but not sure what I am doing wrong

**Comment by thiagocrepaldi** [comment]
I tried this manually and the issue repro too. Maybe we should not use this API for Github Enterprise?

```bash
$ curl -L   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${GH_TOKEN}"   -H "X-GitHub-Api-Version: 2022-11-28"   https://gitenterprise.xilinx.com/api/v3/repos/AMDNeuralOpt/quark-examples/releases/latest
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/enterprise-server@3.12/rest/releases/releases#get-the-latest-release"
}
```

**Comment by zanieb** [comment]
I think this is the same as #49 / https://github.com/astral-sh/ruff-action/pull/56

**Comment by eifinger** [comment]
@thiagocrepaldi can you please try again with a different branch of this action?

```yaml
- name: Install the latest version of ruff
  uses: astral-sh/ruff-action@do-not-assume-github-token
  with:
    github_token: ${{ secrets.FULL_ACCESS_TOKEN }}
    publish_dir: build/html
```
