### ISSUE TITLE
add a way to retrieve the output

### ISSUE THREAD

**Issue by nicola-lunghi** [astral-sh/ruff-action#78]
Hi I need to save the output of the ruff check in a file.
Is it possible?

also how can I not run anything but just install the ruff command for later use? I need to use it in a script

**Comment by eifinger** [comment]
Please see this comment for saving to a file: https://github.com/astral-sh/ruff-action/issues/28#issuecomment-2532702995

**Comment by eifinger** [comment]
Using it like this will invoke ruff to only print the version.

```yaml 
- uses: astral-sh/ruff-action@v3
  with:
    args: "--version"
```

I will maybe add a feature that you can set args to an empty string so ruff is not invoked at all, e.g. `args: ""`

**Comment by nicola-lunghi** [comment]
Thanks!!!

**Comment by nicola-lunghi** [comment]
one thing is not clear how can I get the output in the pr as annotations?

**Comment by eifinger** [comment]
> one thing is not clear how can I get the output in the pr as annotations?

Have you followed the issue I linked but you still don't see annotations?

**Comment by nicola-lunghi** [comment]
> > one thing is not clear how can I get the output in the pr as annotations?
> 
> Have you followed the issue I linked but you still don't see annotations?

yes I don't see them
do you have an example pipeline? is it possible to get annotations for ruff format --diff?

**Comment by nicola-lunghi** [comment]
Hi I've changed my action to:

```yaml
  ruff-linter:
    runs-on: [self-hosted, Ubuntu-22.04]
    permissions:
      contents: read
      pull-requests: write
    steps:
      # need to go first as it cleans the directory
      - uses: actions/checkout@v4
        with:
          clean: true
      - uses: actions-ext/astral-sh-ruff-action@v3
        with:
          version: ${{ env.RUFF_VERSION }}

  ruff-format:
    runs-on: [self-hosted, Ubuntu-22.04]
    permissions:
      contents: read
      pull-requests: write
    steps:
      # need to go first as it cleans the directory
      - uses: actions/checkout@v4
        with:
          clean: true
      - uses: actions-ext/astral-sh-ruff-action@v3
        with:
          version: ${{ env.RUFF_VERSION }}
          args: "format --diff"

```

Now I get the annotations.

questions:
1. its possible to get the annotations on the pr page as well?
2. how to get annotation for the ruff format check?
